### ISSUE TITLE
Not display correctly on Safari

### ISSUE THREAD

**Issue by CptBreeza** [rubysamurai/material_design_lite-sass#3] opened 2015-08-21 01:54 UTC
On Chrome the page displays correctly
![1](https://cloud.githubusercontent.com/assets/9390244/9399670/40839b14-47ea-11e5-8303-76fa0e0baff3.png)
While on Safari it seems that something goes wrong
![2](https://cloud.githubusercontent.com/assets/9390244/9399687/56e6ccfa-47ea-11e5-861a-9819cd9d5c5a.png)
But if I include the material.min.css directly from Google that page displays corrently on Safari
![3](https://cloud.githubusercontent.com/assets/9390244/9399702/836cafc4-47ea-11e5-85f0-ba60d36993b8.png)

**Comment by rubysamurai** [comment] 2015-08-21 12:44
Could you please provide HTML code example? Using, for instance, [codepen.io](http://codepen.io/pen/)

**Comment by CptBreeza** [comment] 2015-08-21 14:50
@rubysamurai
http://codepen.io/cbasic7/pen/LVKJQM
For this pen I include the CSS and JavaScript files directly from Google so the page displays correctly

**Comment by CptBreeza** [comment] 2015-08-22 07:55
@rubysamurai 
And it seems not quite compatible with Turbolinks.

**Comment by rubysamurai** [comment] 2015-08-23 08:11
@cbasic7 
Sorry for the delay. It seems, that MDL website is using a modified version of css file for that dashboard template. Because for me when I modify your codepen by including official MDL css file `https://storage.googleapis.com/code.getmdl.io/1.0.4/material.indigo-pink.min.css`, like [this](http://codepen.io/anon/pen/GJVRrx), then the example is displayed incorrectly in Safari too, but when switch back to `http://www.getmdl.io/templates/dashboard/material.min.css` file, it seems normal. So I can only assume, this is an issue with a dashboard template example.

As for Turbolinks, sadly, this is how Turbolinks was designed. And most frameworks that include JavaScript components suffer from this (bootstrap-sass, foundation etc.), so there is nothing much we can do, unless MDL team decide to support Turbolinks. And untill then we can either follow Turbolinks style and modify JavaScript code manually, consider disabling Turbolinks or use [jQuery Turbolinks](https://github.com/kossnocorp/jquery.turbolinks).

**Comment by althras** [comment] 2015-08-23 08:27
I am now facing this problem as well. Including material design lite through your gem causes safari to completely mess up (too many things messes up basically to describe), but overriding it by linking directly from https://storage.googleapis.com/code.getmdl.io/1.0.4/material.min.css, it works fine. Works totally fine for Chrome though. Something is wrong here.

**Comment by rubysamurai** [comment] 2015-08-23 08:54
This is strange. I'll do more testing on Safari.
If you have any examples, illustrating the problem, that would be a great help.

Update:
I was able to reproduce this issue, will try to isolate and fix it asap.

**Comment by CptBreeza** [comment] 2015-08-23 09:39
@rubysamurai 
Thanks.It says by Google that

> It doesn't rely on any JavaScript frameworks or libraries.

So I don't think jQuery Turbolinks would work.I will try to contact Google for the Safari issue.

**Comment by CptBreeza** [comment] 2015-08-23 09:52
@rubysamurai 
While......If I include MDL directly from https://storage.googleapis.com/code.getmdl.io/1.0.4/material.min.css it works perfectly on Safari.

**Comment by rubysamurai** [comment] 2015-08-23 10:00
@cbasic7 
Does this [codepen](http://codepen.io/anon/pen/GJVRrx) work properly for you in Safari? Because for me it looks exactly as on your initial screenshot.

Anyway there is indeed a bug with missing css elements for webkit browsers in the Sass version and I'm working on it.

**Comment by CptBreeza** [comment] 2015-08-23 10:04
Yes.It works properly on Safari as I expect.

**Comment by rubysamurai** [comment] 2015-08-23 11:16
Found the problem, sorry, that it took so long. Pushed v1.0.4.1 just now, that hopefully solve the issue.

You might need to clear cache after update to get rid of old cached css files `rake tmp:clear`. Let me know if you still experience incorrect behavior with this version.

**Comment by CptBreeza** [comment] 2015-08-23 11:28
Ya......It works.Thanks a lot!

**Comment by althras** [comment] 2015-08-23 11:36
Yep. Safari layouts fixed now. Odd quirk with Textfields floating labels not working disappeared after `rake tmp:clear`. Nice :+1:

**Comment by rubysamurai** [comment] 2015-08-23 11:38
Thanks for help and patience.

Closing this issue.

**Closed as completed by rubysamurai** 2015-08-23 11:38 UTC
Labels: bug
